<a href="https://colab.research.google.com/github/jennadof/Numpy_Panda_assignment/blob/main/Assignment_pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1) Generate an array of zeroes using inbuilt numpy function.
import numpy as np
print(np.zeros((5,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [2]:
#2) Run the given code and find the dot product of both arrays.
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

a.dot(b)



[[7 6 9 7]
 [9 8 3 3]
 [8 5 6 2]]
[[9 9 7]
 [8 5 6]
 [8 8 8]
 [4 7 5]]


array([[211, 214, 192],
       [181, 166, 150],
       [168, 159, 144]])

In [4]:
#3)Read the csv file provided using pandas and display the first 5 entries

import pandas as pd 
data = pd.read_csv('/content/drive/MyDrive/data.csv')
data.head()


OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

In [5]:
#4)Describe the data with all features.
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [6]:
#5)Find the total count of missing values for each feature.
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [8]:
#Display all the unique values from the 'DESCRIPTION’ column.
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [10]:
data['DESCRIPTION'].value_counts()

State Park               13
State Recreation Area     7
State Natural Area        2
State Nature Preserve     2
Interpretive Center       1
Name: DESCRIPTION, dtype: int64

In [11]:
#Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

group_table = data.groupby('DESCRIPTION').mean()
group_table

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [12]:
#8)Generate a random sample of 10 rows from the data.

data.sample(n = 10)

OBJECTID                             UNIT_NAME            DESCRIPTION  \
24        42   Pelican Point State Recreation Area  State Recreation Area   
21        43   Pembina Gorge State Recreation Area  State Recreation Area   
7         28            Lewis and Clark State Park             State Park   
4         25             Grahams Island State Park             State Park   
20        41     Missouri River State Natural Area     State Natural Area   
17        38   Fahlgren Park State Recreation Area  State Recreation Area   
2         23       Fort Abraham Lincoln State Park             State Park   
12        35  Butte St. Paul State Recreation Area  State Recreation Area   
3         24                Fort Ransom State Park             State Park   
6         27             Lake Metigoshe State Park             State Park   

      ACRES  SHAPE.AREA  SHAPE.LEN  
24    25.22    0.000013   0.026357  
21  1236.98    0.000615   0.338800  
7    524.81    0.000256   0.130420  
4    959.33    0.000469   0.125546  
20   174.39    0.000083   0.087192  
17    21.56    0.000010   0.013294  
2    836.47    0.000399   0.119868  
12    51.23    0.000025   0.022095  
3    933.78    0.000444   0.128733  
6   1508.53    0.000751   0.212196

In [13]:
data.shape

(25, 6)

In [ ]:
#9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [14]:
data["New_feature"] = np.random.rand(25)


In [15]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  New_feature  
0   0.135641     0.847863  
1   0.080067     0.355640  
2   0.119868     0.399418  
3   0.128733     0.439200  
4   0.125546     0.578205

In [16]:
data['New_feature']

0     0.847863
1     0.355640
2     0.399418
3     0.439200
4     0.578205
5     0.457728
6     0.881476
7     0.296416
8     0.220476
9     0.442632
10    0.633012
11    0.557564
12    0.268455
13    0.841367
14    0.112957
15    0.351361
16    0.875846
17    0.385303
18    0.751363
19    0.081834
20    0.832271
21    0.126460
22    0.787771
23    0.908009
24    0.874297
Name: New_feature, dtype: float64

In [17]:
#10) Replace zero value of column 'OBJECTID' with mean value permanently.
data.OBJECTID = data.OBJECTID.replace(0, data.OBJECTID.mean())
data.OBJECTID

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64